### PR TITLE
License BoltBot under GNU AGPLv3

### PR DESCRIPTION
**Pull request by Techtony96**
Currently BoltBot is unlicensed, which means that all code is under exclusive copyright by default. In order to change to GNU AGPLv3, I need all contributors to sign their name below agreeing to this change. 

If you are a contributor, please comment on this issue stating `I, @mention, approve relicensing BoltBot to AGPLv3.`

### CODE REVIEW

**Comment by Techtony96** [comment]
I, @Techtony96, approve relicensing BoltBot to AGPLv3.

**Comment by Spikex21** [comment]
I, @Spikex21, approve relicensing BoltBot to AGPLv3.

**Comment by jstrahler** [comment]
I, @jstrahler, approve relicensing BoltBot to AGPLv3.

**Comment by LegitJesseee** [comment]
I, @LegitJesseee, approve relicensing BoltBot to AGPLv3.

**Pull request merged**
